# This script is generated by SensorGatewayUtil.sh to run the custom sensor. The data is embbeded at the end of this file.
# This script can run standalone. For deploying it on gateway, please check the distribution version (in ./motor_status-distribution)
# The settings of the sensor is:
#    Dataset = condenser_rule.csv
#    Maxlines = 0
#    Columns = 1,3 
#    Protocol = mqtt 
#    Frequency = 5
# This script requires sensor.tar.gz in the same folder. If not, please uncomment following line.
# wget https://github.com/tuwiendsg/iCOMOT/raw/master/examples/sensors/sensor.tar.gz

# replace the data
sed '1,/^START OF DATA/d' $0 > data.csv
mv data.csv config-files/data.csv

# configure the sensor in META-INF

sed -i 's#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.dryrun.Dryrun" />#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.mqtt.MQProducer" />#' config-files/META-INF/wire.xml
sed -i 's#<property name="updateRate" value=.*#<property name="updateRate" value="5"/>#' config-files/META-INF/wire.xml

# run the sensor
#java -cp 'bootstrap_container-0.0.1-SNAPSHOT-jar-with-dependencies.jar:*' container.Main
bash container_run.sh
exit 0

START OF DATA
id,name,time,motor_status
condenser_rule,motor_status,Apr 1 2011 12:00:08 AM,1
condenser_rule,motor_status,Apr 1 2011 12:30:08 AM,1
condenser_rule,motor_status,Apr 1 2011 01:00:08 AM,1
condenser_rule,motor_status,Apr 1 2011 01:30:08 AM,1
condenser_rule,motor_status,Apr 1 2011 02:00:08 AM,1
condenser_rule,motor_status,Apr 1 2011 02:30:08 AM,1
condenser_rule,motor_status,Apr 1 2011 03:00:08 AM,1
condenser_rule,motor_status,Apr 1 2011 03:30:08 AM,1
condenser_rule,motor_status,Apr 1 2011 04:00:08 AM,1
condenser_rule,motor_status,Apr 1 2011 04:30:08 AM,1
