# This script is generated by SensorGatewayUtil.sh to run the custom sensor. The data is embbeded at the end of this file.
# This script can run standalone. For deploying it on gateway, please check the distribution version (in ./chw_supply_temp-distribution)
# The settings of the sensor is:
#    Dataset = evaporator_fouling.csv
#    Maxlines = 0
#    Columns = 1,4 
#    Protocol = mqtt 
#    Frequency = 5
# This script requires sensor.tar.gz in the same folder. If not, please uncomment following line.
# wget https://github.com/tuwiendsg/iCOMOT/raw/master/examples/sensors/sensor.tar.gz

# replace the data
sed '1,/^START OF DATA/d' $0 > data.csv
mv data.csv config-files/data.csv

# configure the sensor in META-INF

sed -i 's#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.dryrun.Dryrun" />#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.mqtt.MQProducer" />#' config-files/META-INF/wire.xml
sed -i 's#<property name="updateRate" value=.*#<property name="updateRate" value="5"/>#' config-files/META-INF/wire.xml

# run the sensor
#java -cp 'bootstrap_container-0.0.1-SNAPSHOT-jar-with-dependencies.jar:*' container.Main
bash container_run.sh
exit 0

START OF DATA
id,name,time,difference_oat_and_con_temp
evaporator_fouling,chw_supply_temp,Apr 1 2011 12:00:01 AM,13.82
evaporator_fouling,chw_supply_temp,Apr 1 2011 12:30:01 AM,12.72
evaporator_fouling,chw_supply_temp,Apr 1 2011 01:00:01 AM,12.68
evaporator_fouling,chw_supply_temp,Apr 1 2011 01:30:01 AM,13.62
evaporator_fouling,chw_supply_temp,Apr 1 2011 02:00:01 AM,13.81
evaporator_fouling,chw_supply_temp,Apr 1 2011 02:30:01 AM,12.67
evaporator_fouling,chw_supply_temp,Apr 1 2011 03:00:01 AM,12.34
evaporator_fouling,chw_supply_temp,Apr 1 2011 03:30:01 AM,13.66
evaporator_fouling,chw_supply_temp,Apr 1 2011 04:00:01 AM,13.6
evaporator_fouling,chw_supply_temp,Apr 1 2011 04:30:01 AM,12.38
